{
    'name': 'Real Estate Management',
    'version': '1.0',
    'category': 'Real Estate',
    'summary': 'Manage Real Estate',
    'description': """Manage Real Estate Custom Module""",
    'author': 'Mohamed Anwar',
    'website': 'https://www.odoo.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/real_estate_security.xml',
        'security/ir.model.access.csv',
        'data/property_type_data.xml',
        'views/property.xml',
        'views/agent.xml',
        'views/lease.xml',
        'views/sale.xml',
        'views/tenant.xml',
        'views/menus.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install' : False,
    'application': True,
}